import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import clsx from "clsx";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={clsx(
                    [geistSans, geistMono].map((f) => f.variable),
                    `antialiased`,
                    `bg-[#faf8f0] text-[#9c8a7c]`,
                    `mx-auto max-w-6xl`,
                )}
            >
                <header className="py-6">
                    <h1 className="text-4xl font-bold">
                        <span>hex</span>
                        <span>2048</span>
                    </h1>
                </header>
                <main className="flex flex-row justify-center">{children}</main>
            </body>
        </html>
    );
}
